Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,17 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-# Run tests in all files within the 'test' directory
+      # Build the project
+      - name: Build project
+        run: npm run build
+
+      # Validate branch name
+      - name: Validate branch name
+        if: "!startsWith(github.ref, 'refs/heads/name/')"
+        run: |
+          echo "Branch name does not follow the required pattern."
+          exit 1
+          # Run tests in all files within the 'test' directory
       - name: Run tests in 'test' directory
         run: |
          if [ -d test ]; then  # Check if the 'test' directory exists
@@ -39,14 +49,3 @@ jobs:
          else
           echo "'test' directory not found. Skipping tests."
           fi
-
-      # Build the project
-      - name: Build project
-        run: npm run build
-
-      # Validate branch name
-      - name: Validate branch name
-        if: "!startsWith(github.ref, 'refs/heads/name/')"
-        run: |
-          echo "Branch name does not follow the required pattern."
-          exit 1
